fix(dropdown): applied roving tabindex technique to selected dropdown items
microsoft/fluent-ui-react pull request #1004
Opened 2019-03-01 16:22 UTC by silviuavram

Without it, when in a Popup and a selected item is focused, shift tab will make focus escape the Popup, as FocusTrapZone will not handle it as first focusable item in the Popup (due to the lack of tabindex="0").

Also it does not hurt to be able to come back to the selected item via tab/shift tab once you tabbed/shift tabbed away.

2019-03-01 16:29 UTC, mnajdova commented on packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
> +      this.itemRef.current.setAttribute('tabindex', '0')
We definitely should start extracting behavior for the Dropdown component, we have too much coupling of accessibility concerns in the component... That way we would test this things separately.

2019-03-01 16:30 UTC, mnajdova approved these changes
Approved, just update the changelog, and let's start with extracting these things to behavior

2019-03-01 18:29 UTC, layershifter requested changes
What it is the reason to use DOM API?

---

```jsx
<Label tabIndex={active ? 0 : -1} />
```

https://codesandbox.io/s/wnnlqm80w8?module=/example.js

2019-03-04 12:03 UTC, layershifter approved these changes

2019-03-05 13:28 UTC, merged