Docs/accessibility
microsoft/fluent-ui-react pull request #167
Opened 2018-08-31 13:15 UTC by hughreeling

Adding accessibility on top of PR 152 - adding theming documentation.

2018-09-04 14:12 UTC, jurokapsiar commented on docs/src/views/Accessibility.tsx
> +    <p>Integration of accessibility testing into the DocSite is under consideration.</p>
Stardust basics and Using DocSite probably do not need to be here since the user already is using doc site

2018-09-04 14:14 UTC, jurokapsiar commented on docs/src/views/Accessibility.tsx
> +    </p>
probably not directly related to accessibility - should we move to some more generic part?

2018-09-05 18:03 UTC, kohlikohl commented on docs/src/views/Accessibility.tsx
> +      will apply the role.
Would it be worth adding an example of the generated elements here as well?

2018-09-06 10:45 UTC, hughreeling commented on docs/src/views/Accessibility.tsx
> +    </p>
I think this is important to have here to set scope - so it's clear that these are aspects we're not handling - Can't immediately think of better place to put this.

2018-09-06 11:22 UTC, hughreeling commented on docs/src/views/Accessibility.tsx
> +      will apply the role.
Added.

2018-09-06 11:22 UTC, hughreeling commented on docs/src/views/Accessibility.tsx
> +    <p>Integration of accessibility testing into the DocSite is under consideration.</p>
Updated

2018-09-14 12:02 UTC, kolaps33 approved these changes

2018-09-18 09:27 UTC, kuzhelov commented on docs/src/views/Accessibility.tsx
> +    <Header as="h1" content="Accessibility" />
frankly, this was a bit surprising to see this section just here after reading for a while. Actually, broadly applicable thesisis are mentioned here, so I may suggest to introduce this right at the top of the page, as a first thing user will see.

2018-09-18 09:42 UTC, kuzhelov commented on docs/src/components/ExampleSnippet/ExampleSnippet.tsx
> +const ExampleSnippet = ({
sorry, just to be sure - where this one is used?

2018-09-18 09:56 UTC, kuzhelov commented on docs/src/views/Accessibility.tsx
> +      it's own library components and as a component that can be added by the user.
it is a bit hard to get the idea of this last sentense

2018-09-18 10:50 UTC, kuzhelov requested changes
lets agree on whether we do need ExampleSnippet component that is introduced in this PR first - and merge afterwards

2018-09-18 11:05 UTC, kuzhelov approved these changes
agreed to remove `ExampleSnippet`

2018-09-18 13:09 UTC, merged