feat(Icons): Added missing lock icon
microsoft/fluent-ui-react pull request #872
Opened 2019-02-10 16:15 UTC by priyankar205

2019-02-11 02:59 UTC, codepretty commented
The lock with keyhole is a deprecated design for Teams theme. Please use the icons-lock from the ProcessedIcons folder.

2019-02-11 12:10 UTC, kuzhelov commented on CHANGELOG.md
> +- Export `lock-new` SVG icon @priyankar205 ([#872](https://github.com/stardust-ui/react/pull/872))
would like @codepretty to take a look on this PR before merge

2019-02-11 15:59 UTC, kuzhelov requested changes
is waiting for resolution from design team

2019-02-18 15:38 UTC, alinais commented
@priyankar205 , @codepretty I believe that this PR doesn't make sense after the merge of #906, right?

2019-02-18 15:38 UTC, closed without merging